#!/usr/bin/env ruby

require 'yaml'

hosts = YAML.load(File.read(File.expand_path("~/.sshbook.yml")))
host = hosts[ARGV[0]]
address = host['user'] + '@' + host['host']

puts "Connecting to " + address
# puts "Command: ssh " + host['options'] + " " + address
exec("ssh #{host['options']} #{address}")